version: '3'

services:
   archimage:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    command: /bin/bash 
    volumes:
      - $PWD:/data

volumes:
  data:
